import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

interface WorkoutExercise {
  name: string
  sets: number | null
  reps: string | null
  weight_suggestion: string | null
  rest_seconds: number | null
  notes: string | null
}

interface WorkoutDay {
  name: string
  day_of_week: number | null
  exercises: WorkoutExercise[]
}

interface WorkoutWeek {
  week_number: number
  name: string | null
  workouts: WorkoutDay[]
}

interface MealFood {
  name: string
  serving_size_g: number
  calories: number
  protein_g: number
  carbs_g: number
  fat_g: number
}

interface MealEntry {
  meal_type: string
  foods: MealFood[]
}

interface MealDay {
  day_number: number
  meals: MealEntry[]
}

interface GoalEntry {
  title: string
  category: string
  target_value: number
  target_unit: string
  target_date: string
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { type, data } = await request.json()

    if (!type || !data) {
      return NextResponse.json(
        { error: "Type and data are required" },
        { status: 400 }
      )
    }

    switch (type) {
      case "workout":
      case "cardio": {
        const weeks = data.weeks as WorkoutWeek[]
        if (!weeks?.length) {
          return NextResponse.json(
            { error: "No weeks in plan data" },
            { status: 400 }
          )
        }

        // Create workout plan
        const { data: plan, error: planError } = await supabase
          .from("workout_plans")
          .insert({
            user_id: user.id,
            name: `AI Generated ${type === "cardio" ? "Cardio" : "Workout"} Plan`,
            description: `Generated by AI on ${new Date().toLocaleDateString()}`,
            source: "generated",
            duration_weeks: weeks.length,
            is_active: true,
            parsed_data: data,
          })
          .select("id")
          .single()

        if (planError) throw planError

        for (const week of weeks) {
          const { data: weekRow, error: weekError } = await supabase
            .from("plan_weeks")
            .insert({
              plan_id: plan.id,
              week_number: week.week_number,
              name: week.name,
            })
            .select("id")
            .single()

          if (weekError) throw weekError

          for (let wi = 0; wi < week.workouts.length; wi++) {
            const workout = week.workouts[wi]
            const { data: workoutRow, error: woError } = await supabase
              .from("plan_workouts")
              .insert({
                plan_week_id: weekRow.id,
                day_of_week: workout.day_of_week,
                name: workout.name,
                sort_order: wi,
              })
              .select("id")
              .single()

            if (woError) throw woError

            for (let ei = 0; ei < workout.exercises.length; ei++) {
              const ex = workout.exercises[ei]

              // Find or create exercise
              let exerciseId: string | null = null
              const { data: existing } = await supabase
                .from("exercises")
                .select("id")
                .eq("user_id", user.id)
                .ilike("name", ex.name)
                .limit(1)

              if (existing && existing.length > 0) {
                exerciseId = existing[0].id
              } else {
                const { data: newEx } = await supabase
                  .from("exercises")
                  .insert({
                    user_id: user.id,
                    name: ex.name,
                    is_custom: false,
                  })
                  .select("id")
                  .single()
                if (newEx) exerciseId = newEx.id
              }

              await supabase.from("plan_exercises").insert({
                plan_workout_id: workoutRow.id,
                exercise_id: exerciseId,
                exercise_name: ex.name,
                sets: ex.sets,
                reps: ex.reps,
                weight_suggestion: ex.weight_suggestion,
                rest_seconds: ex.rest_seconds,
                notes: ex.notes,
                sort_order: ei,
              })
            }
          }
        }

        return NextResponse.json({ success: true, planId: plan.id })
      }

      case "meal": {
        const days = data.days as MealDay[]
        if (!days?.length) {
          return NextResponse.json(
            { error: "No days in meal plan data" },
            { status: 400 }
          )
        }

        const today = new Date()

        for (let di = 0; di < days.length; di++) {
          const day = days[di]
          const date = new Date(today)
          date.setDate(date.getDate() + di)
          const dateStr = date.toISOString().slice(0, 10)

          for (const meal of day.meals) {
            // Create meal record
            const { data: mealRow, error: mealError } = await supabase
              .from("meals")
              .insert({
                user_id: user.id,
                date: dateStr,
                meal_type: meal.meal_type,
              })
              .select("id")
              .single()

            if (mealError) throw mealError

            // Create foods and meal items
            for (const food of meal.foods) {
              // Create food in user's library
              const { data: foodRow } = await supabase
                .from("foods")
                .insert({
                  user_id: user.id,
                  name: food.name,
                  serving_size_g: food.serving_size_g,
                  serving_label: `${food.serving_size_g}g`,
                  calories_per_serving: food.calories,
                  protein_g: food.protein_g,
                  carbs_g: food.carbs_g,
                  fat_g: food.fat_g,
                  is_custom: true,
                  is_favorite: false,
                })
                .select("id")
                .single()

              await supabase.from("meal_items").insert({
                meal_id: mealRow.id,
                food_id: foodRow?.id || null,
                custom_name: food.name,
                servings: 1,
                calories: food.calories,
                protein_g: food.protein_g,
                carbs_g: food.carbs_g,
                fat_g: food.fat_g,
              })
            }
          }
        }

        return NextResponse.json({ success: true })
      }

      case "goals": {
        const goals = data.goals as GoalEntry[]
        if (!goals?.length) {
          return NextResponse.json(
            { error: "No goals in data" },
            { status: 400 }
          )
        }

        for (const goal of goals) {
          await supabase.from("goals").insert({
            user_id: user.id,
            title: goal.title,
            category: goal.category,
            target_value: goal.target_value,
            target_unit: goal.target_unit,
            target_date: goal.target_date,
            status: "active",
          })
        }

        return NextResponse.json({ success: true })
      }

      default:
        return NextResponse.json(
          { error: `Unknown type: ${type}` },
          { status: 400 }
        )
    }
  } catch (err) {
    console.error("Generate save error:", err)
    return NextResponse.json(
      { error: "Failed to save generated plan" },
      { status: 500 }
    )
  }
}
